SET(CMAKE_SYSTEM_NAME Windows)
SET(GNU_HOST x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${GNU_HOST}-gcc)
set(CMAKE_CXX_COMPILER ${GNU_HOST}-g++)
SET(CMAKE_RC_COMPILER ${GNU_HOST}-windres)

set(CMAKE_CROSSCOMPILING_EMULATOR wine)

if(NOT DEFINED MINGW_ROOT)
  set(MINGW_ROOT $ENV{MINGW64_ROOT})
endif()

set(ZLIB_ROOT ${MINGW_ROOT})
set(GMP_ROOT ${MINGW_ROOT})
